version: '3.8'
services:
  nginx:
    container_name: nginx
    build:
      dockerfile: nginx.dockerfile
      context: .
    image: nginx
    restart: always
    ports:
    - "80:80"
    networks:
      - api-network
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
    - app
    - app1

  postgresdb:
    image: postgres
    restart: always
    environment:
     - POSTGRES_USER =postgres
     - POSTGRES_PASSWORD=Ta2506f
     - POSTGRES_DB=postgresdb
    ports:
      - "5432:5432"
    networks:
      - api-network

  flyway:
    image: flyway/flyway
    container_name: flyway_migration
    command: ["-url=jdbc:postgresql://postgresdb:5432/postgres", "-user=postgres", "-password=Ta2506f", "migrate"]
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - "postgresdb"

  app:
    build:
      dockerfile: Dockerfile
      context: .
    image: api_app
    container_name: api_app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Ta2506f
      - spring.flyway.enabled=true
      - spring.flyway.baseline-on-migrate=true
    ports:
      - "8080"
    networks:
      - api-network
    depends_on:
      - "postgresdb"

  app1:
    build:
      dockerfile: Dockerfile
      context: .
    image: api_app
    container_name: api_app-1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Ta2506f
      - spring.flyway.enabled=true
      - spring.flyway.baseline-on-migrate=true
    ports:
      - "8080"
    networks:
      - api-network
    depends_on:
      - "postgresdb"   

networks:
  api-network:
    driver: bridge