version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: alissonferreiraevangelista/api-app-local
    container_name: api_app_local
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Ta2506f
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ta2506f
      - POSTGRES_DB=postgresdb
    ports:
      - "5432:5432"
