name: Deploy

on:
  workflow_dispatch: {}

jobs:
  todosimpleapp-deploy:
    name: Deploy | Docker-compose
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy Prognosticare to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          # Github path
          source: "**"
          # VPS path
          target: "~/prognosticare"    
  
      - name: Create Prognosticare env.properties file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/prognosticare
            rm env.properties
            touch env.properties

            # Adicione suas variáveis de ambiente ao arquivo env.properties
            echo "DATASOURCE_URL=${{ secrets.DATASOURCE_URL }}" >> env.properties
            echo "DATASOURCE_USERNAME=${{ secrets.DATASOURCE_USERNAME }}" >> env.properties
            echo "DATASOURCE_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }}" >> env.properties
            echo "MAIL_HOST=${{ secrets.MAIL_HOST }}" >> env.properties
            echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> env.properties
            echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> env.properties
            echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> env.properties
            echo "TOKEN=${{ secrets.TOKEN }}" >> env.properties
            echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> env.properties
            echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> env.properties
            echo "CLIENT_URI=${{ secrets.CLIENT_URI }}" >> env.properties
            echo "PWD_DEFAULT=${{ secrets.PWD_DEFAULT }}" >> env.properties

      - name: Build and Start Docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/prognosticare
            mkdir -p postgres-data
            chmod -R 777 postgres-data
            docker-compose build --no-cache
            docker-compose up -d

